jobs:
- pysparkJob:
    args:
     - --gcs_path_raw=gs://%%BUCKET_NAME%%/raw-%%TIMESTAMP%%/
     - --gcs_path_transformed=gs://%%BUCKET_NAME%%/transformed-%%TIMESTAMP%%/
    mainPythonFileUri: gs://%%BUCKET_NAME%%/scripts/spark_average_speed.py
  stepId: spark_average_speed
placement:
  managedCluster:
    clusterName: final-cluster-wft
    config:
      gceClusterConfig:
        zoneUri: %%REGION%%-a
      masterConfig:
        diskConfig:
          bootDiskSizeGb: 100
          bootDiskType: pd-standard
        machineTypeUri: n2-standard-2
        minCpuPlatform: AUTOMATIC
        numInstances: 1
        preemptibility: NON_PREEMPTIBLE
      workerConfig:
        diskConfig:
          bootDiskSizeGb: 100
          bootDiskType: pd-standard
        machineTypeUri: n2-standard-2
        minCpuPlatform: AUTOMATIC
        numInstances: 2
        preemptibility: NON_PREEMPTIBLE
